### ISSUE TITLE
UI层发送select sound事件太频繁

### ISSUE THREAD

**Issue by ourandream** [ba-archive/ba-story-player#110]
突然发现在哪里点一下都会触发select sound, 猜测ui层的问题

**Comment by notnotype** [comment]
点击屏幕就会发送，是故意的

**Comment by ourandream** [comment]
> 点击屏幕就会发送，是故意的

这可不兴故意， 现在就算正常点击让对话继续也一直响， 太吵了

**Comment by notnotype** [comment]
我记得游戏里面也是这样的

**Comment by Mark9804** [comment]
这个绝对没有，我经常一路手动skip，这个声音只有做选择还有点击控件才有

**Comment by notnotype** [comment]
ok，那把这一行删了
https://github.com/ba-archive/ba-story-player/blob/2fb5503aa1e05735ca6390d0234cc9fd7f7e25c1/lib/layers/uiLayer/BaUI.vue#L143

**Comment by luckyray-fan** [comment]
是不是玩的雀魂, 点击就响😂
