### ISSUE TITLE
开场边框用动态计算的方式自适应

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/ba-story-player#114]
![image](https://user-images.githubusercontent.com/41864956/226101789-f3b0ad42-dce8-4042-a552-c67be0b28ecf.png)

**Comment by ourandream** [comment]
其实官方就是这样（
![image](https://user-images.githubusercontent.com/71924104/226102918-826b55f0-43b9-4894-a8cd-9f8ea8dfc4d3.png)
