### ISSUE TITLE
[chore] format code 应使用 git hook, 在提交时完成

### ISSUE THREAD

**Issue by luckyray-fan** [ba-archive/ba-story-player#141]
现有的 format 流水线使 commit 中出现较多无用的信息

![image](https://user-images.githubusercontent.com/38815993/227725805-ec0d5a59-f27f-4774-872a-c8bb14bb67fa.png)

使用 **husky** 等工具, 进行自动 **eslint fix** 等

**Comment by luckyray-fan** [comment]
https://juejin.cn/post/7005459733427519501

**Comment by luckyray-fan** [comment]
可以把主应用那边也加一下

**Comment by ourandream** [comment]
56038f9
