### ISSUE TITLE
对人物signal的判断似乎有误

### ISSUE THREAD

**Issue by ourandream** [ba-archive/ba-story-player#163]
例子: 兔女郎时100675  index 27
在charactername中Shape为none, 但在游戏中有全息效果

**Comment by diyigemt** [comment]
![image](https://user-images.githubusercontent.com/41864956/236111022-e3cb65d2-e281-43d5-be00-702ac42c8e34.png)

会不会是因为这个

nx到底是怎么让这堆东西跑起来的

**Comment by Mark9804** [comment]
有没有可能是之前他们使用的是shape，现在弃用了换成script方法了

**Comment by diyigemt** [comment]
fix at #172
