### ISSUE TITLE
wa和ruby同时出现导致解析不正确的问题

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/ba-story-player#166]
31160:40

![_3YA$MG)IBGT9{}NR_KBC 6_tmb](https://user-images.githubusercontent.com/41864956/235817957-915260d4-09c7-412a-a552-fd01ac0984f0.jpg)

**Comment by ourandream** [comment]
有一个bug, 如果在这句话点击一下让它快速显示, 后面的字就不会出现了
![image](https://user-images.githubusercontent.com/71924104/235850998-abf75275-7b8d-4767-8c5d-b8c8bdd0c57f.png)
就一直保持上面的状态

**Comment by diyigemt** [comment]
那估计是wa之类的问题了

**Comment by ourandream** [comment]
3a6b006012736d6e94a3fcdb70ee522d653aa36d
