### ISSUE TITLE
人物显示逻辑有问题

### ISSUE THREAD

**Issue by ourandream** [ba-archive/ba-story-player#183]
![image](https://user-images.githubusercontent.com/71924104/236708255-104c2f92-9056-4a3b-bb8f-b84387b0dc90.png)

31030:62

**Comment by diyigemt** [comment]
准确来说 31030:58

**Comment by ourandream** [comment]
![image](https://github.com/ba-archive/ba-story-player/assets/71924104/b74ec465-05bd-4c37-8d3f-b2848a2d419a)
跳转还有问题, 跳回57后问题依然存在

**Comment by diyigemt** [comment]
如果是跳转功能那就不急，这玩意bug多了去了，不差这一个，更何况还有一堆不知道能跳转的
