### ISSUE TITLE
UI_FX_HorSwipe_RtoL_Out在启用强制横屏时有误

### ISSUE THREAD

**Issue by ourandream** [ba-archive/ba-story-player#191]
https://user-images.githubusercontent.com/71924104/236801450-78b976d0-93ab-4622-a051-3ca7a1e7a285.mp4

**Comment by diyigemt** [comment]
这是模拟的横屏吗

**Comment by ourandream** [comment]
> 这是模拟的横屏吗

是的, 把element旋转模拟横屏, 这么一看, 感觉也可能是模拟横屏没有正确把播放器移到中间导致的bug

**Comment by ourandream** [comment]
> 要不趁机把这些html实现全改成基于pixi的 总感觉再这样下去苹果ie又要找我们麻烦了

因为这些特效涉及到文字层和ui层, 恐怕不太行

**Comment by Mark9804** [comment]
实机测试更诡异

https://user-images.githubusercontent.com/9006264/237061096-e9a9f0e9-0e7d-4235-824c-0c8adad1a51c.mov

**Comment by diyigemt** [comment]
> > 要不趁机把这些html实现全改成基于pixi的 总感觉再这样下去苹果ie又要找我们麻烦了
> 
> 因为这些特效涉及到文字层和ui层, 恐怕不太行

准确点是transition的，目前看来只有这个出问题了

**Comment by diyigemt** [comment]
100672:50

**Comment by diyigemt** [comment]
草率了，可能还得是html实现 #192 
但是苹果ie那边怎么办

**Comment by Mark9804** [comment]
如果想彻底解决这个问题，就得把textlayer也下放到pixi里面

**Comment by diyigemt** [comment]
> 如果想彻底解决这个问题，就得把textlayer也下放到pixi里面

不止文字层，ui也得

所以苹果ie那边怎么办，能不能顺便帮我看看什么情况，我怀疑还是样式问题

夸夸

**Comment by Mark9804** [comment]
> 苹果ie那边怎么办，能不能顺便帮我看看什么情况

mac上非全屏就和幻想展示的一样，手机上没东西，也没报错，明天我换个iPad看看

**Comment by Mark9804** [comment]
下周三给你看看，最近太忙了

**Comment by diyigemt** [comment]
> 下周三给你看看，最近太忙了

夸夸

**Comment by diyigemt** [comment]
试试最新的refactor/transition分支?

**Comment by Mark9804** [comment]
> 试试最新的refactor/transition分支?

iphone 能正常播放了

**Comment by diyigemt** [comment]
> > 试试最新的refactor/transition分支?
> 
> iphone 能正常播放了

那其他地方呢

![)0~ S06AGTG23VGB5A9@W 7](https://github.com/ba-archive/ba-story-player/assets/41864956/23091b06-0874-4031-8dcd-ddc49a0a29a6)

**Comment by Mark9804** [comment]
还，，还有哪些地方啊

**Comment by diyigemt** [comment]
哦，，哦对，幻想怎么说

**Comment by ourandream** [comment]
> 哦，，哦对，幻想怎么说

我这也没问题了

**Comment by diyigemt** [comment]
夸夸

**Comment by diyigemt** [comment]
fix at #200
