### ISSUE TITLE
新ruby效果

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/ba-story-player#194]
解决ruby随着被ruby的打印移动的问题

**Comment by diyigemt** [comment]
@ourandream 看看 fix/ruby呗 感觉怪怪的

**Comment by ourandream** [comment]
> @ourandream 看看 fix/ruby呗 感觉怪怪的

确实怪怪的, ruby和普通文字的打字机效果是独立的, 导致看起来和之前下面的文字显示完再打印ruby一样

或许可以先让文字显示出来在fadeout来实现打字机?

**Comment by diyigemt** [comment]
> > @ourandream 看看 fix/ruby呗 感觉怪怪的
> 
> 确实怪怪的, ruby和普通文字的打字机效果是独立的, 导致看起来和之前下面的文字显示完再打印ruby一样
> 
> 或许可以先让文字显示出来在fadeout来实现打字机?

现在呢，感觉还行

**Comment by ourandream** [comment]
> 现在呢，感觉还行
是可以, 但如果ruby的文字正好要换行, 效果会非常奇怪

**Comment by Mark9804** [comment]
先这样吧，暂时把优先级放到两个白子的 live2d 适配后面

另外我在考虑让前端团队了解一下 l2d 的适配业务流程，幻想有空能不能写一个小小的文档，大概记录一下关键步骤

**Comment by ourandream** [comment]
> 先这样吧，暂时把优先级放到两个白子的 live2d 适配后面
> 
> 另外我在考虑让前端团队了解一下 l2d 的适配业务流程，幻想有空能不能写一个小小的文档，大概记录一下关键步骤

ok, 这几天有空了写在wiki上

**Comment by diyigemt** [comment]
我觉得吧，现在有什么手段能知道一段文字会不会换行吗
![)0~ S06AGTG23VGB5A9@W 7](https://github.com/ba-archive/ba-story-player/assets/41864956/4894f30f-da04-4cee-9aae-7d6cde16a67d)
不要太抽象了
