### ISSUE TITLE
enhancement: 忽视 log 标签

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/ba-story-player#204]
棒子把调试标签扔进来忘记删了

![4ae7f553361720ea9f2702cce76a0535](https://github.com/ba-archive/ba-story-player/assets/9006264/6de49a80-d24b-4354-9235-b52aba5ba6f4)

**Comment by Mark9804** [comment]
100705:42

**Comment by diyigemt** [comment]
fix at #205
