### ISSUE TITLE
Tooltip 样式错误

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/ba-story-player#209]
<img width="950" alt="image" src="https://github.com/ba-archive/ba-story-player/assets/9006264/4ff8a8ac-b1b6-4c09-87ba-014077e2177e">

**Comment by Mark9804** [comment]
100702:80
100702:82

文件在群里

**Comment by diyigemt** [comment]
![image](https://github.com/ba-archive/ba-story-player/assets/41864956/5fb300cc-131c-4b6b-9e98-2a282d890626)
![)0~ S06AGTG23VGB5A9@W 7](https://github.com/ba-archive/ba-story-player/assets/41864956/07fb7951-f3ec-4d9b-98cf-4445a50aac89)

**Comment by Mark9804** [comment]
啊哈哈 player库确实复现不了

**Comment by Mark9804** [comment]
和之前哪个问题来着是同一个毛病

![Uploading image.png…]()

**Comment by Mark9804** [comment]
fixed in #211
