### ISSUE TITLE
打字机单元对于空数组的处理，应立即返回 done

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/ba-story-player#213]
~~就算nexon有99%的问题，你就没有1%的问题吗.jpg~~

100703:128

<img width="339" alt="image" src="https://github.com/ba-archive/ba-story-player/assets/9006264/09a3084b-93b4-4890-b634-310ea8a5b484">

这种结构会被解析成空数组，无法完成

**Comment by diyigemt** [comment]
呜呜呜
