### ISSUE TITLE
自动模式下对next事件无响应

### ISSUE THREAD

**Issue by notnotype** [ba-archive/ba-story-player#29]
自动模式下点击屏幕触发next事件应该将当前字幕显示完毕并且立刻加载下一个字幕。
当前会在加载完字幕后停顿许久

**Comment by ourandream** [comment]
自动模式会在文字加载后停顿一下, 让用户查看文字, 以保证自动模式下用户的体验. 停顿时会无视next. 后面应该会添加一个多次next后继续推进的修改, 但目前优先度不高.

**Comment by ourandream** [comment]
5b82f18
