### ISSUE TITLE
选项会阻塞菜单操作

### ISSUE THREAD

**Issue by Mark9804** [ba-archive/ba-story-player#32]
当出现选项时右上角菜单的 log 和快进均不能弹出，选项选择事件结束后会全部堆在画面中

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/9006264/220152939-caca91f4-faef-44e8-ac57-7c57a8b1283c.png">
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/9006264/220153091-737e7abb-05a2-4cc5-8e51-3ab13c98b0cd.png">

**Comment by notnotype** [comment]
最新commit无法复现，你是不是把选项的posision: absolute删了

**Comment by Mark9804** [comment]
草草草 原来是用来做这个的吗
