### ISSUE TITLE
文字层缺失功能

### ISSUE THREAD

**Issue by ourandream** [ba-archive/ba-story-player#37]
- [x] to be continue
- [x] next chapter [实例](https://www.bilibili.com/video/BV1VT4y1o78h?t=239.5&p=8)
- [x] 跳出的视频
- [x] 跳出的图片展示 
- [x] st smooth  [实例](https://www.bilibili.com/video/BV1qg41137ux?t=137.6)

**Comment by diyigemt** [comment]
fix in #50
