### ISSUE TITLE
翻译层支持title、subtitle和ruby结构

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/ba-story-player#48]
如图，标题是有副标题的
![QQ图片20230227225934](https://user-images.githubusercontent.com/41864956/221598539-0f2da693-b9d3-45b8-a951-abf0f47c7977.jpg)

- [x] 翻译层支持subtitle

- [x] 翻译层title解析支持ruby
- [x] 文字层删除subtitle兼容代码

- [x] 文字层showTitle支持ruby

**Comment by Mark9804** [comment]
其实还有一种含 ruby 的标题

<img width="991" alt="image" src="https://user-images.githubusercontent.com/9006264/221640989-8e4e4b66-6f38-4b2c-85c9-75321036126c.png">

**Comment by diyigemt** [comment]
麻麻的
![image](https://user-images.githubusercontent.com/41864956/221725110-7e21d104-9bb8-45ef-acb4-398d7ab5202c.png)

**Comment by diyigemt** [comment]
fix at #73
