### ISSUE TITLE
popup image 和 popup video关闭问题

### ISSUE THREAD

**Issue by diyigemt** [ba-archive/ba-story-player#49]
连续的popup image script长这样，对应 [vol3第一章13话](https://www.bilibili.com/video/BV1VT4y1o78h?t=294.6&p=4)
![image](https://user-images.githubusercontent.com/41864956/221747894-e5244b4a-e584-43d1-8a70-3d62a8ec733a.png)

那么就有两种解决方案

1. 每次next时由文字层主动关闭popup，next后再有popup再显示
2. 由story controller每次判断是否有popup，如果上次有这次没有就发送close popup事件

**Comment by ourandream** [comment]
这个应该是story controller的工作,

**Comment by ourandream** [comment]
已添加hidepopup事件, 可以加相关处理了

**Comment by diyigemt** [comment]
fix at [5ab7f8f](https://github.com/ba-archive/ba-story-player/commit/5ab7f8f4ae2878c6d6243d53912f16fdd3521253)
