### ISSUE TITLE
文字层st已知bug

### ISSUE THREAD

**Issue by ourandream** [ba-archive/ba-story-player#54]
- [x] st smooth不接受clearst
- [x] 字体大小计算有误, vol3第一章第一节最后的字体太小

**Comment by ourandream** [comment]
> 说起来哪里能找到第三章的json，目前这几个branch我都没看到有 以及这俩能给个快速定位的story index吗

https://yuuka.diyigemt.com/story/vol3

可在左边的工具里设故事json为31010, 初始index为49

**Comment by diyigemt** [comment]
要不要大胆假设一下stArg[2]就是字体大小，
太小的原因是你没给我

![image](https://user-images.githubusercontent.com/41864956/222032149-b41046a4-9fe8-4a54-8f4b-a16000321d22.png)

**Comment by ourandream** [comment]
> 要不要大胆假设一下stArg[2]就是字体大小， 太小的原因是你没给我
> 
> ![image](https://user-images.githubusercontent.com/41864956/222032149-b41046a4-9fe8-4a54-8f4b-a16000321d22.png)

之前不就说这个大概是字体大小嘛, 还讨论怎么以yunka l2d文字的60算

**Comment by ourandream** [comment]
> 之前字体大小不是塞在text effects里的吗

我的, 剧情里st文字大小和不同对话框文字大小是分开的, 忘记把st的参数填进去了

**Comment by diyigemt** [comment]
好好好，那就当作st的大小是stArg[2]

**Comment by diyigemt** [comment]
fix at [57fd9ad](https://github.com/ba-archive/ba-story-player/commit/57fd9ad7731a510242cabbaaa29232634b0a2544)
