### ISSUE TITLE
特效层 zmc存在bug

### ISSUE THREAD

**Issue by ourandream** [ba-archive/ba-story-player#56]
猜测是缩放大小算法有误

位置 [vol3 第一章 第8节](https://www.bilibili.com/video/BV1qg41137ux?t=9.0&p=8)

**Comment by diyigemt** [comment]
fix at: #78

**Comment by Mark9804** [comment]
现在的 zmc 好像缩放倍率太高了，可以再改改

小雪剧情1刚开始的时候正确的缩放结果应该是落到门那边的
