### ISSUE TITLE
某些浏览器安装pwa后剧情播放器无法进入全屏

### ISSUE THREAD

**Issue by ourandream** [ba-archive/ba-story-player#70]
目前仅能在android edge复现

**Comment by Mark9804** [comment]
有截图吗

**Comment by ourandream** [comment]
> 有截图吗

![image](https://user-images.githubusercontent.com/71924104/223024150-a00b1fe8-2fbd-44cf-9f7f-f7388a978336.png)

看了眼log没报错, 好像requestFullscrren一直在pending, 挺奇怪的, 后面再看看把吧

**Comment by Mark9804** [comment]
试试看把这一行注释掉然后 `pnpm preview` 全屏看看，如果问题解决了就说明是 pwa 的问题；

https://github.com/ba-archive/blue-archive-story-viewer/blob/768ca6dcd096ed97605ed166b2f10210b14a8b14/vite.config.ts#L107

或者直接在 dev 环境复现，dev 环境没有 pwa

**Comment by Mark9804** [comment]
alook 也有同样的问题

**Comment by ourandream** [comment]
> 试试看把这一行注释掉然后 `pnpm preview` 全屏看看，如果问题解决了就说明是 pwa 的问题；
> 
> https://github.com/ba-archive/blue-archive-story-viewer/blob/768ca6dcd096ed97605ed166b2f10210b14a8b14/vite.config.ts#L107
> 
> 或者直接在 dev 环境复现，dev 环境没有 pwa

测试了一下, 并不能解决
而且如果添加pwa, 连直接从edge打开网页都不能全屏里, 移除后恢复正常

**Comment by Mark9804** [comment]
播放器的 master 分支不能复现，仅能在主站复现？

如果新开一个项目引入我们的包能复现吗

**Comment by ourandream** [comment]
> 播放器的 master 分支不能复现，仅能在主站复现？
> 
> 如果新开一个项目引入我们的包能复现吗

试着新开了一个项目, 写了一个背景是红色的element然后requestfullscreen, 失败, 看来是edge自己的问题, 只要安装了pwa就没法全屏了

**Comment by Mark9804** [comment]
我有想法了

https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenerror_event

https://developer.mozilla.org/en-US/docs/Web/API/ScreenOrientation

**Comment by Mark9804** [comment]
> 没报错, 好像requestFullscrren一直在pending

我又没想法了

**Comment by Mark9804** [comment]
现在没有pwa了，从根本上解决了问题
